### ISSUE TITLE
rust: missing features -- membership testing during verification

### ISSUE THREAD

**Issue by zhenfeizhang** [algorand/bls_sigs_ref-fork#3]

**Comment by kwantam** [comment]
I checked, and deserialization (in the pairing(-fork) library) checks for subgroup membership.

Specifically, the into_affine functions in the EncodedPoint trait impls for G1Uncompressed, G1Compressed, G2Uncompressed, and G2Compressed all check that the point is on the curve and in the correct subgroup. See src/bls12_381/ec/g1.rs and g2.rs in the pairing-fork code.

**Comment by zhenfeizhang** [comment]
good to know. Thanks! Closing this issue
